### ISSUE TITLE
PDF build failed when turn on like-wkhtmltopdf

### ISSUE THREAD

**Issue by TanShun** [HollowMan6/mdbook-pdf#15]
If the headers of the Markdown file contain Chinese words, PDF build failed when set `like-wkhtmltopdf = true`:

```
Generating PDF, please be patient...
PDF successfully generated at: /book/book/pdf/output.pdf
2023-03-12 17:32:32 [INFO] (mdbook::book): Running the pdf-outline backend
2023-03-12 17:32:32 [INFO] (mdbook::renderer): Invoking the "pdf-outline" renderer
Traceback (most recent call last):
  File "/usr/local/bin/mdbook-pdf-outline", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdbook_pdf_outline/mdbook_pdf_outline.py", line 135, in main
    add_wkhtmltopdf_like_outline("../html/print.html", reader, writer)
  File "/usr/local/lib/python3.11/site-packages/mdbook_pdf_outline/mdbook_pdf_outline.py", line 48, in add_wkhtmltopdf_like_outline
    dest = reader.named_destinations["/{}".format(id)]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: '/hello-你好-hello'
```

**Comment by HollowMan6** [comment]
Thanks for reporting! This is truely something that I didn't take account of when I developed this. A new release is now available for fixing this: https://pypi.org/project/mdbook-pdf-outline/0.1.1/
